language: python
python:
  - "2.7"
  - "3.6"
install:
  - ./.travis_setup
env:
  matrix:
    - DJANGO=1.9
    - DJANGO=1.10
script:
  - cd ./testproject; coverage run --source=phonenumber_field manage.py test phonenumber_field testapp
after_success:
  coveralls
